---
swagger: "2.0"
info:
  description: "API for fetching exhange rates against EURO"
  version: "2023-02-06T01:55:28Z"
  title: "ExchangeRateAPI"
host: "j8fnoktyyb.execute-api.ap-northeast-1.amazonaws.com"
basePath: "/prod"
schemes:
- "https"
paths:
  /exchange-rate:
    get:
      produces:
      - "application/json"
      responses:
        "200":
          description: "200 response"
          schema:
            $ref: "#/definitions/Empty"
definitions:
  Empty:
    type: "object"
    title: "Empty Schema"
